Add new Conan tribe members
conan-io/website pull request #249
Opened 2021-03-26 16:47 UTC by uilianries

Adding new Conan tribe members.

We need to wait some profile pictures before merging

Related to https://github.com/conan-io/tribe/pull/22

2021-03-26 19:35 UTC, memsharded reviewed
I started to review, but it seems it is still half way, seems most data is outdated. Please ping me when it is ready for review.

2021-03-26 19:35 UTC, memsharded commented on src/js/3_tribe-members.js
> +  },
```suggestion
    image: 'Ihar_Shashura.jpg',
    description: "I am cross-platform (Android, iOS, Linux, macOS, Windows) engineer who passionate about cross-platform solutions based on c++. Had experience with different embedded devices, CAD systems, high-load servers, Video/Audio applications, financial software. M. Sc. in Math. ",
  },
```

2021-03-29 15:32 UTC, memsharded requested changes

2021-03-29 15:32 UTC, memsharded commented on src/js/3_tribe-members.js
> +    linkedin: 'https://www.linkedin.com/in/mpusz/'
```suggestion
```

This is wrong, please double check

2021-03-29 15:46 UTC, uilianries commented on src/js/3_tribe-members.js
> +    linkedin: 'https://www.linkedin.com/in/mpusz/'
Done

2021-03-29 15:50 UTC, memsharded approved these changes

2021-03-29 15:50 UTC, merged