User Stories
conan-io/website pull request #297
Opened 2021-08-23 13:43 UTC by nadavc-jfrog

2021-08-23 15:29 UTC, tapia requested changes
Please be careful not to add generated content to the repo

2021-08-23 15:29 UTC, tapia commented on user-stories.html
> +<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta content="width=device-width,initial-scale=1,shrink-to-fit=no" name="viewport"><meta name="title" content="User Stories"><meta name="de
This file is generated, shouldn't be added to the repo

2021-08-23 15:29 UTC, tapia commented on user-stories/rti.html
> +<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta content="width=device-width,initial-scale=1,shrink-to-fit=no" name="viewport"><meta name="title" content="metaDescription"><meta name=
This directory (`user-stories`) is generated, and shouldn't be added to the repo

2021-08-24 10:31 UTC, nadavc-jfrog commented
@tapia - they are already in `.gitignore`, you have to remove these files from the repo if you don't want them to be tracked.
Please see - https://stackoverflow.com/questions/45400361/why-is-gitignore-not-ignoring-my-files

2021-08-25 07:04 UTC, tapia commented
@nadavc-jfrog Yes, the files mentioned should be removed from the repo, but the reviewer isn't supposed to make changes to the PR, it should be the author (@ncamaa if I'm not mistaken) who fixes it.

2021-08-29 07:21 UTC, nadavc-jfrog commented on user-stories.html
> +<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta content="width=device-width,initial-scale=1,shrink-to-fit=no" name="viewport"><meta name="title" content="User Stories"><meta name="de
@tapia removed.

2021-08-29 07:21 UTC, nadavc-jfrog commented on user-stories/rti.html
> +<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta content="width=device-width,initial-scale=1,shrink-to-fit=no" name="viewport"><meta name="title" content="metaDescription"><meta name=
@tapia removed.

2021-08-30 07:47 UTC, merged